# Generated by Django 3.0.8 on 2020-07-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_sold_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sold_by',
            new_name='listed_by',
        ),
    ]
